version: '3'

services:  
  
  ##############################################
  ##############################################
  ##
  ## KEYCLOAK-DB
  ## PostgreSQL database to persist the IDP data
  ##
  ##############################################
  ##############################################
  keycloak-db:
    image: postgres
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: keycloak-db
    networks:
      - keycloak
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5432:5432
    environment:
      - LOG_MIN_MESSAGES=INFO
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_ADDR=keycloak-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
# This is required to run keycloak behind traefik
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HOSTNAME=keycloak.${DOMAINNAME}
# Tell Postgress what user/password to create
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    command: ["postgres", "-c", "log_min_messages=INFO"]

  #########################################################
  #########################################################
  ##
  ## KEYCLOAK-DB-BACKUP
  ## Script to backup the Keycloak DB on startup and daily
  ##
  #########################################################
  #########################################################
  keycloak-db-backup:
    image: postgres
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: keycloak-db-backup
    networks:
      - keycloak
    volumes:
      - ${KEYCLOAKBACKUP}:/dump
#      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGHOST=keycloak-db
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - BACKUP_NUM_KEEP=7
      - BACKUP_FREQUENCY=1d
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        pg_dump -Fc > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
        (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {} 
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    depends_on:
      - keycloak-db

networks:
  proxy:
    external: true
  keycloak:
    name: keycloak