version: '3.3' 
services: 
  keycloak: 
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    security_opt:
      - no-new-privileges:true
    command: 
      - start 
      - --auto-build
    ports: 
      - 8080:8282
      - 8443:8443
    environment: 
      JDBC_PARAMS: connectTimeout=1000,useSSL=false 
      KC_DB: mysql 
      KC_DB_PASSWORD: ${KC_DB_PASSWORD} 
      KC_DB_SCHEMA: keycloak 
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USER: ${KC_DB_USER} 
      KC_HOSTNAME: ${KC_HOSTNAME} 
      KC_PROXY: edge 
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/applications/keycloak:/var/lib/keycloak/data 
    networks:
      - proxy
    logging: 
      driver: json-file 
      options: 
        max-size: 10m
        max-file: '3'
    labels:
       - "traefik.enable=true"
       - "traefik.docker.network=proxy"
       # Define the URL to access this app
       - "traefik.http.routers.keycloak.rule=Host(`auth.${DOMAIN}`)"
       - "traefik.http.routers.keycloak.entrypoints=http"
       - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
       - "traefik.http.services.keycloak.loadbalancer.server.scheme=https"
       # TLS is used to protect the domain
       - "traefik.http.routers.keycloak-secure.entrypoints=https"
       - "traefik.http.middlewares.keycloak-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.keycloak.middlewares=keycloak-https-redirect"
       - "traefik.http.routers.keycloak-secure.service=keycloak"
       - "traefik.http.routers.keycloak-secure.rule=Host(`auth.${DOMAIN}`)"
       - "traefik.http.routers.keycloak-secure.tls=true"
networks: 
  proxy: 
    external: true