version: '3'

services:
    
  #########################################################
  #########################################################
  ##
  ## KEYCLOAK
  ## Identity provider
  ## Official Image
  #########################################################
  #########################################################
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      #- keycloak

    ports:
      - 8080:8282
      - 8443:8443

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER="${USER}"
      - GROUP="${GROUP}"
      - KEYCLOAK_LOGLEVEL=WARNING
      # Create initial user details
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      ### This is required to run keycloak behind traefik
      - PROXY_ADDRESS_FORWARDING=true
      #- KEYCLOAK_HOSTNAME=keycloak.${DOMAINNAME}

#     - KEYCLOAK_IMPORT=/config.json
      #- DB_VENDOR=postgres
      #- DB_DATABASE=keycloak
      #- DB_ADDR=keycloak-db
      #- DB_USER=${DB_USER}
      #- DB_PASSWORD=${DB_PASSWORD}
#
      ## Tell Postgress what user/password to create
      #- POSTGRES_USER=${DB_USER}
      #- POSTGRES_PASSWORD=${DB_PASSWORD}

    restart: unless-stopped
    labels:
      - "traefik.enabled=true"
      - "traefik.docker.network=proxy"
      # Define the URL to access this app
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.${DOMAIN}`)"

      - "traefik.http.routers.keycloak.entrypoints=https"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8443"

      # TLS is used to protect the domain
      #- "traefik.http.routers.keycloak-secure.entrypoints=https"
      #- "traefik.http.middlewares.keycloak-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.keycloak.middlewares=keycloak-https-redirect"
      #- "traefik.http.routers.keycloak-secure.service=keycloak"
      #- "traefik.http.routers.keycloak-secure.rule=Host(`keycloak.${DOMAIN}`)"
      #- "traefik.http.routers.keycloak.tls=true"
    #depends_on:
    #  - keycloak-db

networks:
  proxy:
    external: true
  #keycloak:
  #  name: keycloak
