http:
 #region routers 
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox
    # dashy:
    #  entryPoints:
    #    - "https"
    #  rule: "Host(`dashboard.prometheontechnologies.com`)"
    #  middlewares:
    #    - dashy
    #    - default-headers
    #    - https-redirectscheme
    #  tls: {}
    #  service: dashy
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole
    homebridge:
      entryPoints:
        - "https"
      rule: "Host(`homebridge.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - https-redirectscheme
      tls: {}
      service: homebridge
    homeassistant:
      # For Homeassistant config, check: https://www.home-assistant.io/integrations/http/#reverse-proxies
      # This relies on Homeassistant using http. No certs are needed in the Homeassistant config.
      entryPoints:
        - "https"
      rule: "Host(`homeassistant.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - https-redirectscheme
      tls: {}
      service: homeassistant
    syncthing:
      entryPoints:
        - "https"
      rule: "Host(`syncthing.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - https-redirectscheme
      tls: {}
      service: syncthing
    truenas:
      entryPoints:
        - "https"
      rule: "Host(`truenas.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - https-redirectscheme
      tls: {}
      service: truenas
    plex:
      entryPoints:
        - "https"
      rule: "Host(`plex.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - https-redirectscheme
      tls: {}
      service: plex
    minio:
      entryPoints:
        - "https"
      rule: "Host(`minio.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - https-redirectscheme
      tls: {}
      service: minio
    rancher:
      entryPoints:
        - "https"
      rule: "Host(`rancher.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - https-redirectscheme
      tls: {}
      service: rancher
    idrac:
      entryPoints:
        - "https"
      rule: "Host(`idrac.prometheontechnologies.com`)"
      middlewares:
        - auth
        - idrac
        - https-redirectscheme
      tls: {}
      service: idrac
    idrac-console:
      entryPoints:
        - "idrac" # REQUIRED for iDRAC virtual console: Create a new TCP entry point in traefik on port 5900
      rule: "Host(`idrac.prometheontechnologies.com`)"
      middlewares:
        - auth
        - idrac
        - https-redirectscheme
      tls: {}
      service: idrac-console
    opnsense:
      entryPoints:
        - "https"
      rule: "Host(`opnsense.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - https-redirectscheme
      tls: {}
      service: opnsense
    pterodactyl:
      entryPoints:
        - "https"
      rule: "Host(`pterodactyl.prometheontechnologies.com`)"
      middlewares:
        - auth
        - frame-deny
        - default-headers
        - https-redirectscheme
      tls: {}
      service: pterodactyl

#endregion
#region services
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.0.100:8006"
        passHostHeader: true
   # dashy:
   #   loadBalancer:
   #     servers:
   #       - url: "http://192.168.0.204:4000"
   #     passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.0.101:80"
        passHostHeader: true
    homebridge:
      loadBalancer:
        servers:
          - url: "http://192.168.0.102:10999"
        passHostHeader: true
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.0.102:10999"
        passHostHeader: true
    syncthing:
      loadBalancer:
        servers:
          - url: "https://192.168.0.103:8384"
        passHostHeader: true
    truenas:
      loadBalancer:
        servers:
          - url: "https://192.168.0.104"
        passHostHeader: true
    plex:
      loadBalancer:
        servers:
          - url: "https://192.168.0.105:32400"
        passHostHeader: true
    minio:
      loadBalancer:
        servers:
          - url: "https://192.168.0.106:9000/"
        passHostHeader: true
    rancher:
      loadBalancer:
        servers:
          - url: "https://192.168.0.107"
        passHostHeader: true
    idrac:
      loadBalancer:
        servers:
          - url: "https://192.168.0.108"
        passHostHeader: true
    idrac-console:
      loadBalancer:
        servers:
          - url: "https://192.168.0.108:5900"
        passHostHeader: true
    opnsense:
      loadBalancer:
        servers:
          - url: "https://192.168.0.109"
        passHostHeader: true
    pterodactyl:
      loadBalancer:
        servers:
          - url: "http://192.168.0.110:80"
        passHostHeader: true
#endregion
  middlewares:
    auth:
      forwardauth:
        address: "http://authentik-server:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    frame-deny:
      headers:
        frameDeny: true
        customFrameOptionsValue: SAMEORIGIN
    dashy:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
        accessControlAllowOriginList:
          - https://dashboard.prometheontechnologies.com
        accessControlMaxAge: 100
        addVaryHeader: true
        frameDeny: false
    default-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customRequestHeaders:
          X-Forwarded-Proto: https

    idrac:
      headers:
        frameDeny: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    gzip:
      compress: {}
    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
