version: '3.7'
services:
    nextcloud-redis:
        image: redis:alpine
        container_name: nextcloud-redis
        hostname: nextcloud-redis
        restart: unless-stopped
        security_opt:
          - no-new-privileges:true
        command: redis-server --requirepass ${REDIS_HOST_PASSWORD} # REPLACE WITH REDIS PASSWORD
        networks:
            - default
    
    nextcloud-app:
        image: lscr.io/linuxserver/nextcloud:latest #nextcloud
        container_name: nextcloud-app
        restart: unless-stopped
        security_opt:
          - no-new-privileges:true
        depends_on:
            - nextcloud-redis
        environment:
            REDIS_HOST: ${REDIS_HOST}
            REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD} # REPLACE WITH REDIS PASSWORD
            PUID: 1000
            PGID: 1000
            TZ: Europe/London
        volumes:
            - ./data:/data
            - ./config:/config
        ports:
            - 4443:443
        labels:
            traefik.enable: true
            traefik.docker.network: proxy
            traefik.http.routers.nextcloud.entrypoints: http
            traefik.http.routers.nextcloud.rule: Host(`cloud.${DOMAIN}`)
            traefik.http.routers.nextcloud-secure.entrypoints: https
            traefik.http.routers.nextcloud-secure.tls: true
            traefik.http.routers.nextcloud-secure.rule: Host(`cloud.${DOMAIN}`)
            traefik.http.routers.nextcloud.middlewares: nc-rep, nc-header, https-redirect
            traefik.http.routers.nextcloud-secure.middlewares: nc-header
            traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
            traefik.http.middlewares.nc-rep.redirectRegex.permanent: 'true'
            traefik.http.middlewares.nc-rep.redirectRegex.regex: https://(.*)/.well-known/(card|cal)dav
            traefik.http.middlewares.nc-rep.redirectRegex.replacement: https://$$1/remote.php/dav/
            traefik.http.middlewares.nc-header.headers.frameDeny: true
            traefik.http.middlewares.nc-header.headers.sslRedirect: true
            traefik.http.middlewares.nc-header.headers.contentTypeNosniff: true
            traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains: true
            traefik.http.middlewares.nc-header.headers.stsPreload: true
            traefik.http.middlewares.nc-header.headers.stsSeconds: 31536000
            traefik.http.middlewares.nc-header.headers.referrerPolicy: same-origin
            traefik.http.middlewares.nc-header.headers.browserXssFilter: true
            traefik.http.middlewares.nc-header.headers.customRequestHeaders.X-Forwarded-Proto: https
            traefik.http.middlewares.nc-header.headers.customResponseHeaders.X-Robots-Tag: none
            traefik.http.middlewares.nc-header.headers.customFrameOptionsValue: SAMEORIGIN
            traefik.http.routers.nextcloud-secure.service: nextcloud
            traefik.http.services.nextcloud.loadbalancer.server.port: 80
            traefik.http.services.nextcloud.loadbalancer.passHostHeader: true
        networks:
            - proxy
            - default

networks:
  proxy:
    external: true