version: '3.7'

services:
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    networks:
      - default
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 

  redis:
    image: redis:latest
    restart: always
    networks:
      - default
    volumes:
      - redis:/var/lib/redis

  nextcloud:
    depends_on:
      - redis
      - db
    image: nextcloud:stable 
    container_name: nextcloud
    volumes:
      - ./files:/var/www/html
    networks:
      - proxy
      - default
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"
      #- "traefik.enable=true"
      #- "traefik.docker.network=proxy"
      #- "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
      #- "traefik.http.routers.nextcloud-secure.rule=Host(`cloud.yourdomain`)"
      #- "traefik.http.routers.nextcloud-secure.service=nextcloud-service"
      #- "traefik.http.services.nextcloud-service.loadbalancer.server.port=80"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 

networks:
  proxy:
    external: true
    
volumes:
  nextcloud-db-data:
    name: nextcloud-db-data
  redis:
    name: nextcloud-redis