version: '3.7'
services:
  homer:
    image: b4bz/homer
    container_name: homer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/www/assets
      - ./data/icons:/www/assets/icons
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      # Define the URL to access this app
      traefik.http.routers.homer.rule: Host(`${SUB_DOMAIN}.${DOMAIN}`)
      traefik.http.routers.homer.entrypoints: http
      traefik.http.services.homer.loadbalancer.server.port: 8080
      # TLS is used to protect the domain
      traefik.http.routers.homer-secure.entrypoints: https
      # Define Headers
      traefik.http.middlewares.homer-headers.headers.customrequestheaders.X-Forwarded-Proto: https
      traefik.http.middlewares.homer-headers.headers.customrequestheaders.Access-Control-Allow-Origin: "*"
      traefik.http.middlewares.homer-headers.headers.customrequestheaders.Access-Control-Allow-Headers: "*"
      traefik.http.middlewares.homer-headers.headers.customrequestheaders.Access-Control-Allow-Credentials: "true"
      traefik.http.middlewares.homer-headers.headers.customrequestheaders.Access-Control-Allow-Methods: "GET, POST, OPTIONS"
      traefik.http.middlewares.homer-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.homer.middlewares: homer-https-redirect, homer-headers
      traefik.http.routers.homer-secure.service: homer
      traefik.http.routers.homer-secure.rule: Host(`${SUB_DOMAIN}.${DOMAIN}`)
      traefik.http.routers.homer-secure.tls: true
    environment:
      INIT_ASSETS: 0
      USER: ${USER}
      GROUP: ${GROUP}
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true
