version: '3.8'

services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/meraki/dashy/dashy_conf.yml:/app/public/conf.yml
      # - /path/to/item-icons:/app/public/item-icons
    ports:
      - 4000:80
    labels:
      - "traefik.enable=false"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://dashboard.prometheontechnologies.com"
      - "traefik.http.routers.dashy.entrypoints=http"
      - "traefik.http.routers.dashy.rule=Host(`dashboard.prometheonechnologies.com`)"
      - "traefik.http.middlewares.dashy-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dashy.middlewares=dashy-https-redirect"
      - "traefik.http.routers.dashy-secure.entrypoints=https"
      - "traefik.http.routers.dashy-secure.rule=Host(`dashboard.prometheontechnologies.com`)"
      - "traefik.http.routers.dashy-secure.tls=true"
      - "traefik.http.routers.dashy-secure.service=dashy"
      - "traefik.http.services.dashy.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"
    expose:
      - 4000
networks:
  proxy:
    external: true
